### ISSUE TITLE
Unavoidable SEVERE message: "Internal registry of java.beans.PropertyEditorManager not found"

### ISSUE THREAD

**Issue by garysheppardjr** [mjiderhamn/classloader-leak-prevention#101]
https://github.com/mjiderhamn/classloader-leak-prevention/blob/590ab0b86c93a5cff219bf5d50f129c2cf423889/classloader-leak-prevention/classloader-leak-prevention-core/src/main/java/se/jiderhamn/classloader/leak/prevention/cleanup/PropertyEditorCleanUp.java#L20-L26

[`PropertyEditorManager`](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/beans/PropertyEditorManager.html) doesn't seem to have a field called `registry`. Under what circumstances would this portion of the code do anything other than print `Internal registry of java.beans.PropertyEditorManager not found`?

**Comment by mjiderhamn** [comment]
The field exists in earlier versions of the JDK. See the JavaDoc of the class
> This has been fixed in Java 7.

I don't remember off the top of my head if we have dropped JDK 1.6 support already. If so, remove this cleanup.

**Comment by garysheppardjr** [comment]
Thanks for the quick reply, @mjiderhamn.

>I don't remember off the top of my head if we have dropped JDK 1.6 support already. If so, remove this cleanup.

If you are still supporting 1.6, maybe it makes sense to use a less severe method than `error`, such as `info` or `debug`.
