### ISSUE TITLE
Catch and rethrow Throwable to prevent accidental leaks from SeparateClassLoaderInvokeMethod

### ISSUE THREAD

**Issue by vlsi** [mjiderhamn/classloader-leak-prevention#141]
Currently, the framework uses `catch(Exception)` so it will miss `Errors` raised within the test code.

https://github.com/mjiderhamn/classloader-leak-prevention/blob/ad0d9be08752bd6e4d42d0863861506c038d41f7/classloader-leak-test-framework/src/main/java/se/jiderhamn/classloader/leak/JUnitClassloaderRunner.java#L120-L123

For instance, `AssertionError` will not surface, and it will be hard to spot the reason for the failure.

Here's an example how `AssertionError` retains the classloader from unloading, and the framework reports "leak detected" instead of "test code has raised `AssertionError`"

<img width="1061" alt="AssertionError retains ClassLoader from unloading" src="https://user-images.githubusercontent.com/213894/224483917-8b4d0097-6229-4268-b046-f9bc9db42d03.png">

**Comment by mjiderhamn** [comment]
@vlsi Can you provide a failing test case? As per branch `#141` (see [here](https://github.com/mjiderhamn/classloader-leak-prevention/compare/%23141)) It seems to be to behave as expected, while if `Exception` is changed to `Throwable` in the code in question, it does not.

**Comment by vlsi** [comment]
> It seems to be to behave as expected

1) What is the reason for catching `Exception` instead of `Throwable`?
2) What is the reason for evaluating leaks in finally even after the test method throws an exception?
3) What is the reason of having `System.err` there?

If you absolutely want reproducing this, try throwing exception from a class that is **loaded** by the custom classloader. In that case, the exception stacktrace would reference the class and prevent it from unloading.

**Comment by mjiderhamn** [comment]
Sorry - had not put my mind in "ClassLoader leak mode" yet (plus existing comments were misleading). Fixed in https://github.com/mjiderhamn/classloader-leak-prevention/commit/ebb50492e7a2f3619be7bafead1024f8d224bf2f.
