### ISSUE TITLE
Add JEditorPane memory leak prevention

### ISSUE THREAD

**Issue by dany52** [mjiderhamn/classloader-leak-prevention#27]
JEditorPane registers different editorKits in sun.awt.AppContext 
(see "SwingUtilities.appContextPut" strings in JEditorPane source)

something like
```java
new JEditorPane("text/plain", "dummy");
```

will be enough to prevent this memory leak

**Comment by mjiderhamn** [comment]
I think I was a bit quick there. It would seem to me that this leak should already be handled by the library via it's call to `javax.imageio.ImageIO.getCacheDirectory()`, that also calls `sun.awt.AppContext.getAppContext()`. Do you see this leak even when using latest version of the library?

I have however updated the list of known offenders to include `JEditorPane`.

**Comment by dany52** [comment]
I used version 1.11.0 when faced with this problem.
```java javax.imageio.ImageIO.getCacheDirectory() ```not enough. I spent a lot of time trying to understand what's going on :)
