### ISSUE TITLE
ClassCastException - use Object instead of java.lang.Objects

### ISSUE THREAD

**Issue by hdeadman** [mjiderhamn/classloader-leak-prevention#34]
On line 969 there is a cast to Objects but the handback variable is only used in methods that expect an Object. In Weblogic I get a:
```
java.lang.ClassCastException: javax.management.ObjectName cannot be cast to java.util.Objects.
```

line 969 - 
```
 final Objects handback = getFieldValue(handbackField, listenerInfo);
```
should it be:
```
 final Object handback = getFieldValue(handbackField, listenerInfo);
```

**Comment by mjiderhamn** [comment]
Thanks for the report Hal. I've released 1.14.1 to fix this, that should propagate to Maven Central shortly.
