### ISSUE TITLE
Testing classes for junit is not available in maven central

### ISSUE THREAD

**Issue by zeldigas** [mjiderhamn/classloader-leak-prevention#35]
Hi,

It seems that tests jar is not available in maven central, and because of that it is not possible to use classes for testing classloader leaks in other projects
- [here](http://search.maven.org/#artifactdetails|se.jiderhamn|classloader-leak-prevention|1.14.1|) is no test jar in list of artifacts
- tried to plug in it to project with dependency, but no luck
```
<dependency>
            <groupId>se.jiderhamn</groupId>
            <artifactId>classloader-leak-prevention</artifactId>
            <version>1.14.1</version>
            <type>test-jar</type>
            <scope>test</scope>
</dependency>
```

To fix that you need to add test-jar goal to jar-plugin. Detail on that can be found here: https://maven.apache.org/guides/mini/guide-attached-tests.html

P.S. maybe it's worth simply introducing new maven module with this helpful junit code?

**Comment by mjiderhamn** [comment]
Hi Dmitry and thanks for the suggestion. I will consider whether test-jar or separate test framework module makes more sense. Until then, feel free to make use of the sources here on GitHub.

**Comment by mjiderhamn** [comment]
Hi again. Long term I'm leaning towards a separate module, but for now I've included the `test-jar` in the 1.15.0 release, so please give it a try with
```xml
<dependency>
  <groupId>se.jiderhamn</groupId>
  <artifactId>classloader-leak-prevention</artifactId>
  <version>1.15.0</version>
  <type>test-jar</type>
</dependency>
```

**Comment by mjiderhamn** [comment]
I have now released the test framework as a separate Maven artifact
```xml
<dependency>
  <groupId>se.jiderhamn</groupId>
  <artifactId>classloader-leak-test-framework</artifactId>
  <version>1.0.0</version>
</dependency>
```

**Comment by zeldigas** [comment]
Great news, thank you!
