### ISSUE TITLE
WeakCollectionCleaner.exit is not static

### ISSUE THREAD

**Issue by michalsvec** [mjiderhamn/classloader-leak-prevention#38]
I have a NPE in fixGeoToolsLeak because exit method in org.geotools.util.WeakCollectionCleaner is not static, so invoke(null) cannot be used. 

I found this method: https://navatintarev.wordpress.com/2012/05/18/geotools-memory-leak/

Could you check pls? If you think that could be a new solution I can prepare a patch.

Thank you.

**Comment by mjiderhamn** [comment]
Thanks for the report!

I created a test case to verify the problem, and released version 1.15.2 to fix it. It should propagate to Maven Central shortly.

**Comment by michalsvec** [comment]
Perfect. Thank you very much!
