### ISSUE TITLE
JRE 7 dependency introduced since v1.15

### ISSUE THREAD

**Issue by kimbamps** [mjiderhamn/classloader-leak-prevention#39]
Since classloader-leak-prevention version 1.15, there was introduced a JRE 1.7 dependency.

Following constructor was only introduced since 1.7 and this will give an error during startup when using an older JRE.

final Constructor<RuntimeException> constructor = 
          RuntimeException.class.getDeclaredConstructor(String.class, Throwable.class, Boolean.TYPE, Boolean.TYPE);

https://docs.oracle.com/javase/7/docs/api/java/lang/RuntimeException.html#RuntimeException(java.lang.String,%20java.lang.Throwable,%20boolean,%20boolean)

In the pom files it still says:
<maven.compiler.source>1.6</maven.compiler.source>
<maven.compiler.target>1.6</maven.compiler.target>

I would suggest to keep the minimum required version to 1.6 since Oracle still supports JAVA 1.6 with their "Long Term Support" program.

**Comment by mjiderhamn** [comment]
Hi @kimbamps!
Yes, in [ClassLoaderLeakPreventor line 558](https://github.com/mjiderhamn/classloader-leak-prevention/blob/master/classloader-leak-prevention/src/main/java/se/jiderhamn/classloader/leak/prevention/ClassLoaderLeakPreventor.java#L558) I try to invoke this constructor added in Java 1.7. However, if that fails, the error should be [caught](https://github.com/mjiderhamn/classloader-leak-prevention/blob/master/classloader-leak-prevention/src/main/java/se/jiderhamn/classloader/leak/prevention/ClassLoaderLeakPreventor.java#L563) and logged as a warning. This means one particular leak mechanism (#36) won't be put in place, but other than that, there should be no problems AFAI can see. I will update the logged warning message to reflect the Java 1.7 requirement.

If you want to avoid the warning altogether, just override [`constructRuntimeExceptionWithoutStackTrace()`](https://github.com/mjiderhamn/classloader-leak-prevention/blob/master/classloader-leak-prevention/src/main/java/se/jiderhamn/classloader/leak/prevention/ClassLoaderLeakPreventor.java#L556) to return `null`.
