### ISSUE TITLE
Use junit rule insted of runner?

### ISSUE THREAD

**Issue by davidkarlsen** [mjiderhamn/classloader-leak-prevention#56]
Would it be possible to get the solution realised with JUnit rules instead of the runner?

**Comment by mjiderhamn** [comment]
The test class needs to be loaded with a separate classloader, and off the top of my head I cannot see how to achieve that with rules.

Is there a reason you need a rule rather than a runner?

**Comment by mjiderhamn** [comment]
Closing due to lack of response from submitter

**Comment by davidkarlsen** [comment]
The reason for wanting a rule and not a runner is to free the runner for other frameworks (camel, spring, etc) it's a more flexible solution
