### ISSUE TITLE
Add Xalan leak prevention

### ISSUE THREAD

**Issue by samuelbr** [mjiderhamn/classloader-leak-prevention#63]
Hi @mjiderhamn,
This is excellent library! I found leak in Xalan library (https://issues.apache.org/jira/browse/XALANJ-2600). It would be great if your library support prevention for this leak.

Thanks.

**Comment by mjiderhamn** [comment]
Hi @samuelbr . Sorry for the super slow response. I've just been able to force trigger this leak under Java 8, and hope to have some prevention mechanisms in place shortly.

Thanks for the report!

**Comment by mjiderhamn** [comment]
Prevention for this is included in recently released version 2.4.0

**Comment by samuelbr** [comment]
Hi @mjiderhamn ,
Thanks
