### ISSUE TITLE
Unexpected bevahior after using the classloader-leak-prevention library,

### ISSUE THREAD

**Issue by vgjosse** [mjiderhamn/classloader-leak-prevention#69]
Hi,
I try to fix a metaspace memory leak when I redeploy a web application in Tomcat (8.5.15).

Before using the classloader-leak-prevention library, the Path To GC Roots gives me
![image](https://user-images.githubusercontent.com/6718435/29525040-bffef13a-8691-11e7-8b05-6558e3a5a71c.png)

After using the library, I got
![image](https://user-images.githubusercontent.com/6718435/29525165-1b09648e-8692-11e7-9749-54ff4fd8b5bf.png)

The library succeed to release some resources, but it creates new threads that are no garbage collected.
Any idea, what goes wrong?

Thanks.

Vincent.

**Comment by mjiderhamn** [comment]
Hi @vgjosse . What version of Oracle JDBC are you using? Seems they may have added something that needs a new prevention mechanism.

**Comment by vgjosse** [comment]
Hi @mjiderhamn. 
I use the latest official release of the Oracle JDBC driver, ojdbc8-12.2.0.1.0.jar.
Please let me know how I can help to fix that new memory leak.
Thanks,
Vincent.

**Comment by vgjosse** [comment]
Hi,
I made progress. I confirm that it is related to the Oracle JDBC driver.
The new threads appear after closing the  Timer-0 and InterruptTimer threads.
Vincent.

**Comment by vgjosse** [comment]
The last one for today :)

In Tomcat, I've configured the JreMemoryLeakPreventionListener such as
`  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" classesToInitialize="oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser,oracle.jdbc.driver.NoSupportHAManager,oracle.net.nt.TimeoutInterruptHandler" />`

Now in the Memory Analyzer, I have 
![image](https://user-images.githubusercontent.com/6718435/29569534-106c1cc0-8754-11e7-9bb6-aa5be80c415b.png)

There is no more icon with the yellow bullet but the application classloader is not garbage collected.
Can you tell me why? The Oracle MBean?

Thanks,

Vincent.

**Comment by mjiderhamn** [comment]
My interpretation is that even though the MBean is not loaded by the classloader in question (the JDBC driver is not in your `.war`, right), it contains a stacktrace that points to one of the classes in your `.war`.

We may need to remove that stacktrace from the MBean somehow.

**Comment by vgjosse** [comment]
Hello,

I confirm that the oracleDiagnosabilityMBean is the one that prevent the application class loader to be garbage collected. I've added the code below to unregister it at the application shutdown.
`	private void unregisterOracleDiagnosabilityMBean() {
		try {
			MBeanServer mBeanServer = ManagementFactory.getPlatformMBeanServer();
			Set<ObjectName> oracleDiagnosabilityMBean = mBeanServer.queryNames(new ObjectName("com.oracle.jdbc:type=diagnosability,*"), null);

			if (oracleDiagnosabilityMBean != null && oracleDiagnosabilityMBean.size() == 1) {
				mBeanServer.unregisterMBean(oracleDiagnosabilityMBean.iterator().next());
			} else {
				LOGGER.warn(
						"The OracleDiagnosabilityMBean has not been unregistred. The MBean search has returned no or more than one result. It could cause a Metaspace memory leak.");
			}
		} catch (JMException e) {
			LOGGER.warn("An exception occured while unregistring OracleDiagnosabilityMBean. It could cause a Metaspace memory leak. Exception {}", e);
		}
	}`

I don't know how you can include that in the memory leak library.

Thanks a lot for your help and all the information you've shared on that topic.

Vincent.

**Comment by mjiderhamn** [comment]
@vgjosse I've now added preventions for both the new TimerThreads and the MBean to the library, in a more proper way than deregistering the MBean. Are you able to verify by compiling the master branch if this fixes the issues you've been seeing?

**Comment by vgjosse** [comment]
Sure, I'll have a look at your modification tomorrow and will let you know if it is ok or not.

**Comment by vgjosse** [comment]
Hi,

With the latest code in the master branch, I still have an issue with the OracleDiagnosabilityMBean.
Please have a look at the below screenshot.

Moreover, you'll have to uncomment line 24 to 54 in OracleJdbcThreadInitiator.

![image](https://user-images.githubusercontent.com/6718435/29915318-ca547644-8e3b-11e7-8765-019a8b967e49.png)

**Comment by mjiderhamn** [comment]
I see. My passing test case was not a correct indicator.

Would you mind trying again with the latest sources?

**Comment by vgjosse** [comment]
Well done. The metaspace memory is now released when I unload the application.

Just think to uncomment line 24 to 54 in OracleJdbcThreadInitiator.

Vincent.

**Comment by mjiderhamn** [comment]
This change is included in version 2.5.0 which was just released.
