### ISSUE TITLE
JMX NotificationListener removal

### ISSUE THREAD

**Issue by ArloL** [mjiderhamn/classloader-leak-prevention#72]
While debugging an issue (https://jira.spring.io/browse/SPR-16027) I noticed that the cleanup of JMX NotificationListeners did not work in my case. I have uploaded the heap dump to <https://www.evosec.de/java_pid9880.hprof>.

![image](https://user-images.githubusercontent.com/195367/31013447-76d37fb4-a516-11e7-893a-0b0de030c2e6.png)

**Comment by mjiderhamn** [comment]
Thanks for the report!

I've made some changes to address this issue. Would it be possible for you to try out your case with the ClassLoader Leak Prevention library compiled from the latest sources, and report back?
