### ISSUE TITLE
Groovy 2.4.13 leaks ClassLoader?

### ISSUE THREAD

**Issue by ArloL** [mjiderhamn/classloader-leak-prevention#77]
After updating an internal Spring Boot application from spring-platform Brussels-SR6 to Brussels-SR7 our [tomcat-classloader-leak-test](https://github.com/evosec/tomcat-classloader-leak-test) fails. Analyzing the Heap Dump gives me this:

![image](https://user-images.githubusercontent.com/195367/35674002-7e8a8a92-0743-11e8-8c77-2ca9d6417726.png)

Which is weird because the Groovy version has not changed. I'll investigate further.

**Comment by mjiderhamn** [comment]
Looks like that would be a soft reference, which is cleared only before an `OutOfMemoryError` would have been thrown. Does your test account for that?

**Comment by ArloL** [comment]
Yes, it does by creating classes with javassist: https://github.com/evosec/tomcat-classloader-leak-test/blob/develop/src/main/java/de/evosec/leaktest/WebAppTest.java#L332

**Comment by ArloL** [comment]
I have tried reproducing the problem unsuccessfully. Therefore I assume everything is OK for now.
