### ISSUE TITLE
Java9+ AccessibleObject (Method/Field) are leaking without setting setAccessible()

### ISSUE THREAD

**Issue by amir-shalem** [mjiderhamn/classloader-leak-prevention#78]
The following code is not leaking in java8, and complains that "ClassLoader has been garbage collected, while test is expected to leak"

but in Java9 this is leaking

I'm not sure yet what is the correct cleanup to fix this bug, but this is happening both in Java9 & Java10
This of course happens with any method or field, I've just randomly used `Thread` in this example

```
@RunWith(JUnitClassloaderRunner.class)
@LeakPreventor(LeakTest.Preventor.class)
public class LeakTest {

  @Test
  @Leaks(dumpHeapOnError = true)
  public void triggerLeak()
      throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
    Method m = Thread.class.getMethod("currentThread");
    m.invoke(null);
  }

  public static class Preventor implements Runnable {
    public void run() {
      // Not sure
    }
  }
}
```

**Comment by amir-shalem** [comment]
I'm able to "fix" this by adding code in `triggerLeak` by adding `m.setAccessible(true)`, 
but thats cheating, since there are many libraries using this pattern, and I can't/won't change them.

**Comment by amir-shalem** [comment]
I found a fix which sounds right, but I still have not fully traced the code in Java source code of why is it happening.

But, if I'm doing that `class.getMethod("...").invoke()` 15 times in the `Preventor` `Runnable`, then the class loader is being cleaned.

**Comment by mjiderhamn** [comment]
Hi @amir-shalem and thanks for the report! I have been able to recreate this using Java 10.0.1. However I have yet to understand the difference compared to Java 8. I'm afraid it might even be something internal to the JVM.

**Comment by amir-shalem** [comment]
I figured out the bug, its because java no longer do bypassing of security checks. And security checks are caching the caller class in `AccessibleObject::securityCheckCache`.

the bug is also possible in Java8, but much harder to reproduce - only happens with protected method/fields.

The bug is that when creating method/accessor/constructor accessors, java pass the current method instead of the `root` method. thus causing that leak (http://hg.openjdk.java.net/jdk/jdk/file/56923ee4f07e/src/java.base/share/classes/java/lang/reflect/Method.java#l635)

I opened a bug report for it https://bugs.openjdk.java.net/browse/JDK-8202113

From what I'm seeing there's no general way to mitigate that, so i don't think there's anything you can do in your project for solving this issue systematically 

Because mitigating that without knowing which methods are "spammed" will require you to traverse all the classes, and all their methods/fields/constructors, and look whether any of them have accessors which are pointing, and fixing the accessor pointer to the root

The reason invoking the method 15 times "solves" the problem is because the accessor is being converted from JNI to bytecode, and no longer points to the method (inflationThreshold)

You can argue that disabling inflationThreshold is one way to solve this, but this will only mitigate the bug method & constructor, and doesn't solve it for fields.

As for mitigating that if you know the methods ahead, you can just call them in PreInitiator stage - and make sure each method is invoked and has its `accessor` ready (and linked to the `appclassloader`), but this is project specific, you can't really predict the reflection which will happen in the future

**Comment by mjiderhamn** [comment]
Thanks for the info @amir-shalem !
Yes, since I haven't found a workaround either I will close this issue.

**Comment by amir-shalem** [comment]
@mjiderhamn For completeness, I want to report that we've missed one portion of this bug, and that calling Class::newInstance() is leaking as well.

This means that if the classloader is calling stuff like: `java.lang.String.class.newInstance()` it will leak the caller.
Bug report: https://bugs.openjdk.java.net/browse/JDK-8206240

the newInstance() method is deprecated and shouldn't be used, but many external projects are using that, and if they are calling classes which are from parent classloader, then they will leak themselves because of the Class cache.

What even worst about this leak, that its not visible at all via MAT, see discussion in http://dev.eclipse.org/mhonarc/lists/mat-dev/msg00515.html

Currently most chances are that this bug won't be fixed for JDK11 release, I'm hoping for JDK12 they will fix it.
I'm going to mitigate it by invalidating those classes cache which are required, by calling their newInstance() as cleanup step, which will "work" - but its hard to find, since MAT can't verify me.
