### ISSUE TITLE
ClassLoaderLeakPreventorFactory.clearPreInitiators() doesn't clear your pre-initiators.

### ISSUE THREAD

**Issue by jervin** [mjiderhamn/classloader-leak-prevention#83]
I am enjoying using your library, just had to do this today to work around a bug:
final ClassLoaderLeakPreventorFactory factory = new ClassLoaderLeakPreventorFactory()
        {
            @Override
            public void clearPreInitiators()
            {
                // There is a bug in the open source codebase, clearly clear preinitiators should clear the preinitiators, it is cleaning the cleanups instead.
                this.preInitiators.clear();
            }
		    
        };

**Comment by mjiderhamn** [comment]
Thanks for the report - sorry for the late reply. This has now been fixed in the Git repo, but not yet released.
