### ISSUE TITLE
Poor extendability

### ISSUE THREAD

**Issue by jbeckers** [mjiderhamn/classloader-leak-prevention#86]
How can I easily subclass ClassLoaderLeakPreventorListener into MyClassLoaderLeakPreventorListener? My goals is to disable some cleanups.

Essentially, I think all that would be needed is for line 205 to become 
`    // Create factory with default PreClassLoaderInitiators and ClassLoaderPreMortemCleanUps
    final ClassLoaderLeakPreventorFactory classLoaderLeakPreventorFactory = createClassLoaderLeakPreventorFactory();`
instead of 
`    // Create factory with default PreClassLoaderInitiators and ClassLoaderPreMortemCleanUps
    final ClassLoaderLeakPreventorFactory classLoaderLeakPreventorFactory = new ClassLoaderLeakPreventorFactory();`

where `createClassLoaderLeakPreventorFactory()` is a template method that my subclass can override as such:
`    protected ClassLoaderLeakPreventorFactory createClassLoaderLeakPreventionFactory() {
        final ClassLoaderLeakPreventorFactory classLoaderLeakPreventorFactory = new ClassLoaderLeakPreventorFactory();
        classLoaderLeakPreventorFactory.removeCleanUp(KeepAliveTimerCacheCleanUp.class);
        return classLoaderLeakPreventorFactory;
    }`

(Right now, extending ClassLoaderLeakPreventorListener to do this, requires dupilcating almost half of the code.)

Would you be open to such a change?

**Comment by mjiderhamn** [comment]
Hi @jbeckers - sorry for the late reply.

Thanks for the suggestion. I have now made such a change, however it is currently not yet released.
