### ISSUE TITLE
2.7.0 not yet available on maven central

### ISSUE THREAD

**Issue by dodgex** [mjiderhamn/classloader-leak-prevention#97]
Hey there,

last week you released 2.7.0. While the release is on github it is still missing on maven central.

Do you plan to publish the release there too?

Thanks! :)

**Comment by mjiderhamn** [comment]
Sorry, there was one final step that had not finished. _Now_ it should be in Maven Central AFAI can see.
Thanks for the heads up!

**Comment by dodgex** [comment]
Looks good, thank you ! :)
